### ISSUE TITLE
Cannot create an interface with just a default implementation

### ISSUE THREAD

**Issue by gabejohnson** [disnet/sweet-algebras#4]
```js
'lang sweet.js';
import { class, interface, implements } from 'sweet-interfaces';

interface I {
  a() {};
}
```
throws
```
evalmachine.<anonymous>:23
  return isBrackets_117(t) || isIdentifier_102(t) || isKeyword_104(t) || isStringLiteral_110(t) || isNumericLiteral(t);
                                                                                                   ^

ReferenceError: isNumericLiteral is not defined
```
It's originating at https://github.com/disnet/sweet-interfaces/blob/f79cdba14cee8297788c443fc435207fc340a10c/src/match-util.js#L29.

I looks like there's may be two bugs here.

One that allowed that code to be reached and another (in sweet.js) that failed to rewrite `isNumericLiteral`.

**Comment by michaelficarra** [comment]
@gabejohnson You have an extra (illegal) semicolon in your interface. Fixed the issue with `isNumericLiteral` by importing it.

**Comment by gabejohnson** [comment]
Ahhhh...so the first bug was me 🐞
